"""Pydantic models for common API response bodies."""

from typing import Annotated, Literal, Self

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    Field,
    PlainSerializer,
    PositiveInt,
    model_validator,
)
from starlette import status

from fml.constants import ABOUT_BLANK
from fml.utils import dt_to_utc_str, utc_now


class CustomBaseModel(BaseModel):
    """Base model for shared library schemas."""


class Message(CustomBaseModel):
    """Simple message response body."""

    message: str


class HealthCheck(CustomBaseModel):
    """Health check response body."""

    status: Literal["up", "down"]
    timestamp: Annotated[
        AwareDatetime, PlainSerializer(dt_to_utc_str, return_type=str)
    ] = Field(default_factory=utc_now)


class Token(CustomBaseModel):
    """Bearer token response body."""

    access_token: str
    token_type: str = "bearer"


class JWTPayload(CustomBaseModel):
    """Registered JWT claims."""

    sub: Annotated[str | None, Field(description="The subject of the JWT")] = None
    iat: Annotated[
        PositiveInt | None,
        Field(
            description="The time (by the number of seconds since the Epoch)"
            " at which the JWT was issued",
            examples=[int(utc_now().timestamp())],
        ),
    ] = None
    exp: Annotated[
        PositiveInt | None,
        Field(
            description="The expiration time (by the number of seconds since the Epoch)"
            " on or after which the JWT MUST NOT be accepted for processing",
        ),
    ] = None

    @model_validator(mode="after")
    def check_exp_gt_iat(self) -> Self:
        """Validate that expiration occurs after the issued-at time."""

        if self.iat is None or self.exp is None:
            return self
        if self.iat >= self.exp:
            raise ValueError(f"exp {self.exp!r} must be greater than iat {self.iat!r}")
        return self


class Error(CustomBaseModel):
    """Detailed error entry for a problem response."""

    detail: Annotated[
        str,
        Field(
            description=(
                "A granular description on the specific error related to "
                "a body property, query parameter, path parameters, and/or header."
            ),
            max_length=4096,
        ),
    ]
    pointer: Annotated[
        str | None,
        Field(
            description=(
                "A JSON Pointer to a specific request body property that is the source of error."
            ),
            max_length=1024,
        ),
    ] = None
    parameter: Annotated[
        str | None,
        Field(
            description=(
                "The name of the query or path parameter that is the source of error."
            ),
            max_length=1024,
        ),
    ] = None
    header: Annotated[
        str | None,
        Field(
            description="The name of the header that is the source of error.",
            max_length=1024,
        ),
    ] = None
    code: Annotated[
        str | None,
        Field(
            description=(
                "A string containing additional provider specific codes "
                "to identify the error context."
            ),
            max_length=50,
        ),
    ] = None


class ProblemDetail(CustomBaseModel):
    """RFC 9457 problem detail response body."""

    type: Annotated[
        str | AnyUrl,
        Field(
            description="A URI reference that identifies the problem type.",
            max_length=1024,
        ),
    ] = ABOUT_BLANK
    status: Annotated[
        PositiveInt,
        Field(
            default=status.HTTP_500_INTERNAL_SERVER_ERROR,
            description=(
                "The HTTP status code generated by the origin server for this occurrence of the problem."
            ),
            ge=status.HTTP_100_CONTINUE,
            le=status.HTTP_511_NETWORK_AUTHENTICATION_REQUIRED,
        ),
    ]
    title: Annotated[
        str,
        Field(
            description="A short, human-readable summary of the problem type.",
            max_length=1024,
        ),
    ]
    detail: Annotated[
        str | None,
        Field(
            description=(
                "A human-readable explanation specific to this occurrence of the problem."
            ),
            max_length=4096,
        ),
    ] = None
    instance: Annotated[
        str | AnyUrl | None,
        Field(
            description=(
                "A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced."
            ),
            max_length=1024,
        ),
    ] = None
    errors: Annotated[
        list[Error] | None,
        Field(
            description=(
                "An array of error details to accompany a problem details response."
            ),
            max_length=1000,
        ),
    ] = None
