from typing import Annotated, Literal

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    Field,
    PlainSerializer,
    PositiveInt,
)
from starlette import status

from fml.constants import ABOUT_BLANK
from fml.utils import dt_to_utc_str, utc_now


class CustomBaseModel(BaseModel): ...


class Message(CustomBaseModel):
    message: str


class HealthCheck(CustomBaseModel):
    status: Literal["up", "down"]
    timestamp: Annotated[
        AwareDatetime, PlainSerializer(dt_to_utc_str, return_type=str)
    ] = utc_now()


class Error(CustomBaseModel):
    """Provides explicit details on a problem towards an API consumer."""

    detail: Annotated[
        str,
        Field(
            description=(
                "A granular description on the specific error related to "
                "a body property, query parameter, path parameters, and/or header."
            ),
            max_length=4096,
        ),
    ]
    pointer: Annotated[
        str | None,
        Field(
            description=(
                "A JSON Pointer to a specific request body property that is the source of error."
            ),
            max_length=1024,
        ),
    ] = None
    parameter: Annotated[
        str | None,
        Field(
            description=(
                "The name of the query or path parameter that is the source of error."
            ),
            max_length=1024,
        ),
    ] = None
    header: Annotated[
        str | None,
        Field(
            description="The name of the header that is the source of error.",
            max_length=1024,
        ),
    ] = None
    code: Annotated[
        str | None,
        Field(
            description=(
                "A string containing additional provider specific codes "
                "to identify the error context."
            ),
            max_length=50,
        ),
    ] = None


class ProblemDetail(CustomBaseModel):
    """An RFC 9457 problem object

    https://www.rfc-editor.org/rfc/rfc9457.html
    """

    type: Annotated[
        str | AnyUrl,
        Field(
            description="A URI reference that identifies the problem type.",
            max_length=1024,
        ),
    ] = ABOUT_BLANK
    status: Annotated[
        PositiveInt,
        Field(
            default=status.HTTP_500_INTERNAL_SERVER_ERROR,
            description=(
                "The HTTP status code generated by the origin server for this occurrence of the problem."
            ),
            ge=status.HTTP_100_CONTINUE,
            le=status.HTTP_511_NETWORK_AUTHENTICATION_REQUIRED,
        ),
    ]
    title: Annotated[
        str,
        Field(
            description="A short, human-readable summary of the problem type.",
            max_length=1024,
        ),
    ]
    detail: Annotated[
        str | None,
        Field(
            description=(
                "A human-readable explanation specific to this occurrence of the problem."
            ),
            max_length=4096,
        ),
    ] = None
    instance: Annotated[
        str | AnyUrl | None,
        Field(
            description=(
                "A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced."
            ),
            max_length=1024,
        ),
    ] = None
    errors: Annotated[
        list[Error] | None,
        Field(
            description=(
                "An array of error details to accompany a problem details response."
            ),
            max_length=1000,
        ),
    ] = None
